name: com.example.simple_cubit_app
description: A simple Flutter app with two screens: a login screen with email and password fields, and a home screen with a logout button.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.3
  mocktail: ^0.2.0

flutter:
  uses-material-design: true